### ISSUE TITLE
gitinspector doesn't work Atlassian Stash repository

### ISSUE THREAD

**Issue by EvanChanSLA** [ejwa/gitinspector#84] opened 2015-11-11 00:40 UTC
Hi,

First, I want to thank you for creating this tool. I am able to run this tool on GITHUB but when I ran this tool on Stash repo that I cloned, it didn't show all the authors associated with commits. We have over 15 authors but it only shows 2 authors. The GITHUB repos seems to show everyone on it.

Please advise.

Thanks in advance,
Evan

**Comment by adam-waldenberg** [comment] 2015-11-11 06:57
Duplicate of issue #75. Please refer to that issue. Gitinspector filters out commits from the statistics based on file type and content. If they are not showing up, they have probably not committed any commits that gitinspector considers valid. 

Use "-l" to see what file types are used and detected by gitinspector. Use "-f" to modify the list of scanned/included file types. Make sure to read through the complete [Documentation](https://github.com/ejwa/gitinspector/wiki/Documentation).

An entry in the [FAQ](https://github.com/ejwa/gitinspector/wiki/FAQ) is probably in order, as this question has been asked twice in a very short time. I'll look into adding that.

**Closed by adam-waldenberg** 2015-11-11 06:57 UTC
Labels: Duplicate
