### ISSUE TITLE
Support for generating consolidated report for multiple repositories

### ISSUE THREAD

**Issue by cpatel** [ejwa/gitinspector#78] opened 2015-10-23 00:39 UTC
Hi,

It would be great to have a feature to take list of repositories on command line and generate consolidated report for all repositories in one. 

Example: 
Let's say I have 2 repositories in directory repo1 and repo2, then I should be able to run something like

"gitinspector --repos repo1,repo2 -F htmlembedded -w > report.html" from parent directory which will generate consolidated report for both repo into report.html

I have tried hack into changes.py for this but looks like it would require some work.

Thanks

**Comment by adam-waldenberg** [comment] 2015-10-23 11:14
Currently being worked on and a duplicate of issue 24.

**Closed by adam-waldenberg** 2015-10-23 11:14 UTC
Labels: Duplicate

**Comment by cpatel** [comment] 2015-10-23 14:15
Missed it. Thanks I will watch that issue.
