### ISSUE TITLE
text output - last committer lacks entry and then "Below are the number of rows..." injects in the same line 

### ISSUE THREAD

**Issue by yarikoptic** [ejwa/gitinspector#102] opened 2016-01-18 14:59 UTC
0.4.3 in debian

```
$ git remote show origin | head -3
* remote origin
  Fetch URL: git://git.kitenet.net/git-annex
  Push  URL: git://git.kitenet.net/git-annex

$ gitinspector                    
Statistical information for the repository 'git-annex' was gathered on 2016/01/18.
The following historical commit information, by author, was found in the repository:

Author                     Commits    Insertions      Deletions    % of changes
Joey Hess                       83        130395           4338           77.36
Sören Brunk             Below are the number of rows from each author that have survived and are still intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Joey Hess                  5140            3.9         34.6                7.53
Sören Brunk                8883           43.7         18.4               18.09
```

**Comment by adam-waldenberg** [comment] 2016-01-19 08:43
This is a duplicate of #101 and is probably related to the progress bar.

**Closed by adam-waldenberg** 2016-01-19 08:43 UTC
Labels: Duplicate

**Comment by yarikoptic** [comment] 2016-01-19 13:44
issue persists with master 6.20160114-57-gdaf852e.  I will provide detail in #101
