### ISSUE TITLE
[feature] Performances

### ISSUE THREAD

**Issue by tetraf** [ejwa/gitinspector#136] opened 2016-12-01 19:23 UTC
Would it be possible to have some sort of caching to enhance performances on report regeneration for big repositories or global report for a lot of repositories?

**Comment by adam-waldenberg** [comment] 2016-12-06 09:54
Already planned and a duplicate of #22. It's a somewhat tricky feature to implement right, but is on the todo list

**Closed** 2016-12-06 09:55 UTC
Labels: Duplicate
