### ISSUE TITLE
'NoneType' object is not iterable due to bug in threading code

### ISSUE THREAD

**Issue by carera** [ejwa/gitinspector#118] opened 2016-06-26 07:15 UTC
Hi

for one particular repository, gitinspector just stopped working

```
Fetching and calculating primary statistics (1 of 2): 99%Traceback (most recent call last):
  File "../gitinspector/gitinspector.py", line 24, in <module>
    gitinspector.main()
  File "/Users/minarikj/apps/gitinspector/gitinspector/gitinspector.py", line 206, in main
    run.process(repos)
  File "/Users/minarikj/apps/gitinspector/gitinspector/gitinspector.py", line 70, in process
    changes = Changes(repo, self.hard)
  File "/Users/minarikj/apps/gitinspector/gitinspector/changes.py", line 222, in __init__
    self.commits = [item for sublist in self.commits for item in sublist]
TypeError: 'NoneType' object is not iterable
```

I am running Mac OS El Capitan 10.11.4
script is being run with Python 2.7

It works for other repositories, and if I `git reset --hard HEAD^` (i.e. hard reset to second last commit), it works for this particular repository as well. The last commit that 'breaks' it containts nothing more than a couple of files changed and added (merge from a PR branch). Now adding a new commit on top of HEAD makes it work again.

**Comment by adam-waldenberg** [comment] 2016-06-26 09:19
Hi. Please see #115 and try to apply that fix. I think this might be related.

**Comment by tomriddly** [comment] 2016-08-19 07:38
@adam-waldenberg I found the issure may cause by uncommited(maybe unpushed?) changes. I think this might be helpful;-)

**Comment by mensfeld** [comment] 2016-11-04 18:08
I have the same problem when using --json (for non json works ok)

**Comment by hindsholm** [comment] 2017-02-23 15:01
I run into this bug consistently on two repositories. There are no uncommitted changes. I am running ver. 0.4.4.

**Comment by adam-waldenberg** [comment] 2017-02-23 15:03
@hindsholm, As you can see from the above discussion, the Issue is well understood... I just haven't had time to sit down and actually fix it yet...

**Comment by hindsholm** [comment] 2017-02-23 15:11
@adam-waldenberg I understand. I just wanted to let you know that the issue will also show up when there are no uncommitted changes :-)

**Comment by adam-waldenberg** [comment] 2017-02-23 15:17
@hindsholm Yes. Thank you. It's actually caused by a logic error in the threading code (overflow), causing it to end up with an empty changeset. In the meantime you can remedy it with the fix mentioned in https://github.com/ejwa/gitinspector/issues/118#issuecomment-258506482.

**Comment by hindsholm** [comment] 2017-02-23 15:44
@adam-waldenberg I have cloned the repo and applied the workaround and I can confirm that it does indeed work :-)

**Comment by mensfeld** [comment] 2017-02-23 15:46
@hindsholm  it needs to work - It runs around 2-5k times per day for me ;)

**Comment by adam-waldenberg** [comment] 2017-05-15 01:08
Should be fixed now. Please report any problems.

**Closed** 2017-05-15 01:07 UTC
Labels: Bug, Priority : High
