### ISSUE TITLE
stability and age calculations

### ISSUE THREAD

**Issue by rafiqkattangere** [ejwa/gitinspector#143] opened 2017-02-07 01:49 UTC
It would be good to document how a user should interpret stability and age? And what those numbers indicate?

**Comment by rafiqkattangere** [comment] 2017-02-07 14:34
I just realized you did answer in issue #111. Having it documented can help. Thanks!

**Comment by adam-waldenberg** [comment] 2017-05-15 01:30
I'm currently working on a document that describes the output from gitinspector. It will be part of the wiki at some point.

Closing this, I'm considering this as a duplicate of issue #111.

**Closed by adam-waldenberg** 2017-05-15 01:30 UTC
Labels: Duplicate

**Comment by schumannd** [comment] 2019-10-29 12:29
Does this document exist somewhere? I couldn't find it in the wiki or the README

**Comment by adam-waldenberg** [comment] 2019-11-11 12:31
@schumannd At the moment it's not properly documented.

You can read about stability here, https://github.com/ejwa/gitinspector/issues/111#issuecomment-218405073

The age is just the average age of all the lines of code that the author currently has active in the repository.
